// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUZGLtGxk6BmviGNVYlViUoqjNaY8V7mQ',
    appId: '1:168400676601:web:ca5f09b01eb73af2c8a428',
    messagingSenderId: '168400676601',
    projectId: 'gaanam-92468',
    authDomain: 'gaanam-92468.firebaseapp.com',
    storageBucket: 'gaanam-92468.firebasestorage.app',
    measurementId: 'G-MSRMSXP8RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPmewPA5vY9EYVD7MO5Lu6cal4AS5yis',
    appId: '1:168400676601:android:a87af2851da56ad0c8a428',
    messagingSenderId: '168400676601',
    projectId: 'gaanam-92468',
    storageBucket: 'gaanam-92468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Syjl12sdtUW_9FXEMbQwno4D2IWQbfM',
    appId: '1:168400676601:ios:eb2a6ff748d20db9c8a428',
    messagingSenderId: '168400676601',
    projectId: 'gaanam-92468',
    storageBucket: 'gaanam-92468.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Syjl12sdtUW_9FXEMbQwno4D2IWQbfM',
    appId: '1:168400676601:ios:eb2a6ff748d20db9c8a428',
    messagingSenderId: '168400676601',
    projectId: 'gaanam-92468',
    storageBucket: 'gaanam-92468.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUZGLtGxk6BmviGNVYlViUoqjNaY8V7mQ',
    appId: '1:168400676601:web:59db6d87c513dec7c8a428',
    messagingSenderId: '168400676601',
    projectId: 'gaanam-92468',
    authDomain: 'gaanam-92468.firebaseapp.com',
    storageBucket: 'gaanam-92468.firebasestorage.app',
    measurementId: 'G-T2XKPVGV5Q',
  );

}